Repository rasterio/affine, pull requests merged in 2024-12, with the labels that each got.

#104 Subtle misc. refactors and lint suggestions
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  affine/__init__.py
  affine/tests/test_pickle.py
  affine/tests/test_rotation.py
  affine/tests/test_transform.py
  docs/src/conf.py
  pyproject.toml
Labels: linting

#103 Compare with self.precision.
  affine/__init__.py
Labels: bug

#108 Add numpy `__array__` interface
  affine/__init__.py
  affine/tests/test_numpy.py
  pyproject.toml
Labels: enhancement

#110 Move source to src/
  .github/workflows/ci.yml
  CHANGES.txt
  README.rst
  pyproject.toml
  src/affine/__init__.py
  src/affine/tests/__init__.py
  src/affine/tests/test_numpy.py
  src/affine/tests/test_pickle.py
  src/affine/tests/test_rotation.py
  src/affine/tests/test_serialize.py
  src/affine/tests/test_transform.py
  tox.ini
Labels: packaging
